export const debugFilters = [
  { id: 'all', label: '全部异常' },
  { id: 'recovering', label: '恢复中' },
  { id: 'blocked', label: '待人工接管' },
  { id: 'healed', label: '已恢复' },
  { id: 'rolled_back', label: '已回滚' },
]

export const recoveryPlaybooks = [
  {
    id: 'retry-fallback',
    name: '重试并切换只读快照',
    trigger: '工具调用超时 / 下游只读可接受',
    steps: ['冻结当前任务上下文', '重试 1 次主通道', '失败后切换只读快照源'],
    guardrails: ['最多重试 2 次', '不得覆盖已确认产物'],
    owner: 'Debug Agent',
  },
  {
    id: 'rollback-last-green',
    name: '回滚到最近稳定版本',
    trigger: '关键验收项连续失败',
    steps: ['定位最近绿色检查点', '撤销异常节点变更', '恢复上游依赖指针'],
    guardrails: ['必须保留审计日志', '需要记录回滚原因'],
    owner: 'Orchestrator',
  },
  {
    id: 'human-gate',
    name: '升级人工闸门',
    trigger: '返工超过 2 轮 / 风险等级过高',
    steps: ['锁定当前 run', '生成问题摘要', '通知人工确认'],
    guardrails: ['停止自动推进', '仅保留只读操作'],
    owner: 'Audit Agent',
  },
]

export const debugRuns = [
  {
    id: 'run-014',
    title: '组装阶段工具超时',
    phase: 'Agent Assembler',
    severity: 'P1',
    status: 'recovering',
    owner: 'Debug Agent',
    updatedAt: '2026-03-24 21:05',
    summary: 'Assembler 在读取工具注册表时超时，当前已进入自动重试与降级恢复流程。',
    trigger: 'tool_registry query 超时 8.2s',
    impact: 'AgentGraph 生成停滞 1 个阶段',
    retryCount: 1,
    canRollback: true,
    strategyId: 'retry-fallback',
    result: {
      headline: '已切换只读快照源，等待下一次心跳确认',
      detail: '当前运行保留原始上下文与任务队列，未触发最终回滚。',
      evidence: ['快照源 registry-cache-v3', '失败节点 A2 / A3', '恢复 ETA 40s'],
    },
    metrics: [
      { label: '最长阻塞', value: '08.2s' },
      { label: '失败节点', value: '2 个' },
      { label: '恢复 ETA', value: '40s' },
    ],
    timeline: [
      { id: 't1', time: '21:01:12', type: 'error', title: '工具注册表读超时', detail: 'Assembler 第一次读取超时，触发异常捕获。' },
      { id: 't2', time: '21:02:03', type: 'analysis', title: 'Debug Agent 收敛错误上下文', detail: '定位到 query key 与缓存失配。' },
      { id: 't3', time: '21:03:28', type: 'recovery', title: '启动重试与快照回退', detail: '保留主链路，切换到只读快照源继续执行。' },
    ],
  },
  {
    id: 'run-015',
    title: '评估闭环返工超限',
    phase: 'Reflection',
    severity: 'P1',
    status: 'blocked',
    owner: 'Audit Agent',
    updatedAt: '2026-03-24 20:48',
    summary: '同一验收项连续返工两轮仍未满足，已触发人工闸门等待确认。',
    trigger: 'ac-002 连续 2 轮未通过',
    impact: '最终交付被挂起',
    retryCount: 2,
    canRollback: false,
    strategyId: 'human-gate',
    result: {
      headline: '自动推进已冻结，等待人工确认是否继续返工',
      detail: '系统已生成问题摘要并锁定 run，防止在错误目标上继续推进。',
      evidence: ['failed item: ac-002', 'needsHuman=true', 'gateType=ir_confirm'],
    },
    metrics: [
      { label: '返工轮次', value: '2 / 2' },
      { label: '挂起时长', value: '18m' },
      { label: '风险等级', value: '高' },
    ],
    timeline: [
      { id: 't1', time: '20:32:44', type: 'review', title: '第一次返工失败', detail: '缺少预算明细与责任人映射。' },
      { id: 't2', time: '20:39:15', type: 'review', title: '第二次返工失败', detail: '补充后仍未满足人工闸门条件。' },
      { id: 't3', time: '20:48:02', type: 'guard', title: '升级人工闸门', detail: 'Planner 已停止自动推进。' },
    ],
  },
  {
    id: 'run-016',
    title: '执行链路批量回滚',
    phase: 'Orchestrator',
    severity: 'P2',
    status: 'rolled_back',
    owner: 'Orchestrator',
    updatedAt: '2026-03-24 19:56',
    summary: '下游错误率持续高于阈值，系统已回滚到最近稳定检查点。',
    trigger: '失败率 11.4% > 阈值 8%',
    impact: '撤销最近 3 个执行节点',
    retryCount: 0,
    canRollback: false,
    strategyId: 'rollback-last-green',
    result: {
      headline: '已回滚到检查点 checkpoint-20260324-1912',
      detail: '所有下游产物恢复到绿色版本，并生成复盘报告待审阅。',
      evidence: ['rollback depth=3', 'checkpoint=1912', 'affected tasks=t3/t4/t5'],
    },
    metrics: [
      { label: '回滚节点', value: '3 个' },
      { label: '恢复耗时', value: '03m 21s' },
      { label: '当前状态', value: '稳定' },
    ],
    timeline: [
      { id: 't1', time: '19:42:30', type: 'error', title: '错误率突破阈值', detail: '连续两个窗口高于 8%。' },
      { id: 't2', time: '19:47:08', type: 'recovery', title: '执行批量回滚', detail: '撤销下游节点并重置依赖。' },
      { id: 't3', time: '19:56:19', type: 'done', title: '回滚完成并通过审计', detail: '已恢复到稳定版本。' },
    ],
  },
  {
    id: 'run-017',
    title: '日志采集延迟已恢复',
    phase: 'Observability',
    severity: 'P3',
    status: 'healed',
    owner: 'Debug Agent',
    updatedAt: '2026-03-24 18:20',
    summary: '日志管道短时积压，自动扩容后恢复。',
    trigger: 'log queue 积压 4.8k',
    impact: '追踪详情展示延迟',
    retryCount: 1,
    canRollback: false,
    strategyId: 'retry-fallback',
    result: {
      headline: '采集管道已恢复到正常吞吐',
      detail: '未影响主执行链路，仅造成观测面板短时延迟。',
      evidence: ['queue back to 320', 'collector replicas 2 -> 3', 'no data loss'],
    },
    metrics: [
      { label: '峰值积压', value: '4.8k' },
      { label: '恢复耗时', value: '06m' },
      { label: '数据丢失', value: '0' },
    ],
    timeline: [
      { id: 't1', time: '18:09:10', type: 'error', title: '日志队列积压', detail: 'collector 吞吐下降。' },
      { id: 't2', time: '18:13:22', type: 'recovery', title: '自动扩容 collector', detail: '副本数由 2 提升为 3。' },
      { id: 't3', time: '18:20:05', type: 'done', title: '积压清空', detail: '指标恢复绿色。' },
    ],
  },
]
